### ISSUE TITLE
Second side on flows bug

### ISSUE THREAD

**Issue by ksen0** [tiny-tool-box/aseq#12]
Expected behavior: If I let the flow (cards 1-3) play through on both sides, I can click on card 1 and it will play through on both sides again

Actual: First way through is okay, but then when I click on card 1, it goes through on the first (yellow) side first and moves on to card4 (triangle) without doing the second side

**Comment by ksen0** [comment]
@ericHgorski Some version of this kind of problem persists. I get different mini-flow behavior when I (1) let the sequence play through the first time vs (2) click on the start of the mini flow later on.

In 1, I see the three cards each turn yellow (is that intentional? It seems like a design choice, I wouldn't have thought of it but to be honest it might be good! Don't change it if it's not a bug, let's touch base about it) and then one by one they turn green and fade out.

In 2, they don't do the mini-flow behavior at all, just one-by-one go thru yellow-green-fade cycle

**Comment by ericHgorski** [comment]
Yes lets chat (that was an intentional design choice) ! What you're describing was an issue with the clicking functionality which I hadn't altered to fit with the refactoring yet. Now it should be working properly.
