### ISSUE TITLE
Timing for asymmetric poses - UX/clarification

### ISSUE THREAD

**Issue by ksen0** [tiny-tool-box/aseq#14]
It's hard to tell right now because timing is not as is written, but duration is on each side. So:

1. On card, if card has other side, it should say "Duration: x mins on each side"
2. Just check if in code that is the case?

**Comment by ericHgorski** [comment]
I am not 1000% positive this is what you meant? But we will talk soon to resolve!

**Comment by ksen0** [comment]
Copy: both sides is still unclear (both sides togehter or separately), "each side" is better, but yes that looks like the right placement

Timing: no idea because it's still sped up but I assume we're on the same page and eg Triangle is 1 min on right, flip, 1 min on left?

If so feel free to close! Thanks!
