### ISSUE TITLE
Various UX comments

### ISSUE THREAD

**Issue by ksen0** [tiny-tool-box/aseq#15]
- [x] With new text (see PR), the first card jumps in size on hover
- [x] "No description" should just be no description imo?
- [x] The title text is not centered within its block (see card0 with new text)
- [x] Looks like when the play is on, clicking on cards toggles and pauses? my "pretending to be a user" expectation would be that if it is currently playing, it continues to playing, just from the new spot? But I'm open to a different interpretation
- [x] *Moved to #19 * First description also contains a link, can you add some ok styling to this? Even just blank underlined text is ok. On page load, all links should have class ('no-play' or something) added to them and when a card is clicked, if that class is present on the `this`, ignore.

**Comment by ericHgorski** [comment]
Ok I believe I fixed most of these. Im a little unsure what the last one means however!

**Comment by ksen0** [comment]
@ericHgorski Looks great, I'm bumping it to next milestone for the last task
