### ISSUE TITLE
Global timer inconsistent pause toggle

### ISSUE THREAD

**Issue by ksen0** [tiny-tool-box/aseq#18]
Minor bug. Observe:

1. Click on the last card and let the sequence "finish." Observe that Pause Button is shown (not correct) but timer is stopped (correct).
2. Click on any card: the cards seems to change color with correct timing. Observe that Pause Button (correct) is shown but timer is stopped (not correct).
3. Let the sequence play through (or click on last card) to let the sequence finish. Observe that Pause Button is shown (not correct) but timer is also running now (not correct).

**Comment by ericHgorski** [comment]
Now behaves as intended!
